services:
  af-api:
    image: harbor.infra.cluster.ionos.com/imagefactory/af-api:build-20260515143318
    restart: unless-stopped
    environment:
      - DEV_MODE=true
    networks:
      - internal

  af-poc:
    build: .
    restart: unless-stopped
    environment:
      - AF_API_URL=http://af-api:8000/api/v1
      - AF_FRONTEND_URL=${AF_FRONTEND_URL:-https://frontendspace.duckdns.org}
      - IONOS_USERNAME=${IONOS_USERNAME}
      - IONOS_PASSWORD=${IONOS_PASSWORD}
      - IONOS_DATACENTER_ID=${IONOS_DATACENTER_ID}
      - IONOS_SERVER_ID=${IONOS_SERVER_ID}
      - IONOS_SERVER_TEMPLATE_ID=${IONOS_SERVER_TEMPLATE_ID}
      - IONOS_SERVER_NAME=${IONOS_SERVER_NAME}
      - IONOS_IMAGE_ALIAS=${IONOS_IMAGE_ALIAS}
      - IONOS_IMAGE_ID=${IONOS_IMAGE_ID}
      - IONOS_RESERVED_IP=${IONOS_RESERVED_IP}
    depends_on:
      af-api:
        condition: service_healthy
    networks:
      - internal

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    depends_on:
      - af-poc

networks:
  internal:

volumes:
  caddy_data:
  caddy_config:
